version: '3'
services:
    itguy_redis:
        container_name: itguy_redis
        image: redis:alpine
    itguy_mongodb:
        container_name: itguy_mongodb
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
        volumes:
            - ${BASEPATH}/mongodb/data/db:/data/db
    itguy_mariadb:
        container_name: itguy_mariadb
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${PASSWORD}
            MYSQL_USER: ${USERNAME}
            MYSQL_PASSWORD: ${PASSWORD}
    itguy_apiman:
        container_name: itguy_apiman
        build: ./apiman
        volumes:
            - ${BASEPATH}/themes/auth:/opt/jboss/wildfly/themes/custom/keycloak
        environment:
            VIRTUAL_HOST: ${APIMAN_DOMAIN}
            VIRTUAL_PATH: /auth
            VIRTUAL_PORT: 8080
            USERNAME: ${USERNAME}
            PASSWORD: ${PASSWORD}
    itguy_wildfly:
        container_name: itguy_wildfly
        build: ./wildfly
        volumes:
            - ${BASEPATH}/themes/web:/opt/jboss/wildfly/themes
        links:
            - itguy_redis:redis
            - itguy_mariadb:mysql
            - itguy_mongodb:mongodb
            - itguy_apiman:apiman
        environment:
            VIRTUAL_HOST: ${WILDFLY_DOMAIN}
            VIRTUAL_PORT: 8080
            USERNAME: ${USERNAME}
            PASSWORD: ${PASSWORD}
    itguy_jenkins:
        container_name: itguy_jenkins
        links:
            - itguy_wildfly:wildfly
            - itguy_apiman:apiman
        environment:
            JENKINS_OPTS: --argumentsRealm.passwd.${USERNAME}=${PASSWORD} --argumentsRealm.roles.${USERNAME}=admin
            VIRTUAL_HOST: ${JENKINS_DOMAIN}
            VIRTUAL_PORT: 8080
    itguy_proxy:
        container_name: itguy_proxy
        image: jwilder/nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        ports:
            - ${HTTP_PORT}:80
            - ${HTTPS_PORT}:443